parameters:
     images_directory: '%kernel.project_dir%/public/uploads/images'
     # Configuration for PayDunya
     paydunya_public_key: '%env(PAYDUNYA_PUBLIC_KEY)%'
     paydunya_private_key: '%env(PAYDUNYA_PRIVATE_KEY)%'
     paydunya_token: '%env(PAYDUNYA_TOKEN)%'
     paydunya_mode: '%env(PAYDUNYA_MODE)%'
     paydunya_master_key: '%env(PAYDUNYA_MASTER_KEY)%'

services:
    # PayDunyaService configuration
    App\Service\PayDunyaService:
        arguments:
            $publicKey: '%paydunya_public_key%'
            $privateKey: '%paydunya_private_key%'
            $masterKey: '%paydunya_master_key%'
            $token: '%paydunya_token%'
            $mode: '%paydunya_mode%'

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
